name: Test Signature

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: 1.25.0
      id: go
    

    - name: Build for Windows
      run: |
        mkdir -p dist
        GOOS=windows GOARCH=amd64 go build -o dist/sshgw.exe main.go
    
    - name: Sign
      uses: ossign/ossign@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        config: ${{ secrets.OSSIGN_CONFIG }}
        inputFiles: dist/*.exe
        fileType: pecoff
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: dist/**
